import type { SupportServiceCategory } from '@/lib/types';

export type ServiceAdminInput = {
  name: string;
  category: SupportServiceCategory;
  zone?: string;
  city?: string;
  address?: string;
  latitude?: number | null;
  longitude?: number | null;
  phone?: string;
  whatsapp_number?: string;
  website_url?: string;
  description?: string;
  price_text?: string;
  meeting_point?: string;
  rating_score?: number | null;
  rating_count?: number | null;
  is_active?: boolean;
  is_published?: boolean;
  is_verified?: boolean;
  source_url?: string;
  notes?: string;
};

export type ServiceAdminRow = {
  id: number;
  name: string;
  category: SupportServiceCategory;
  zone: string | null;
  city: string | null;
  address: string | null;
  latitude: number | null;
  longitude: number | null;
  phone: string | null;
  whatsapp_number: string | null;
  website_url: string | null;
  description: string | null;
  price_text: string | null;
  meeting_point: string | null;
  rating_score: number | null;
  rating_count: number | null;
  is_active: boolean;
  is_published: boolean;
  is_verified: boolean;
  source_url: string | null;
  notes: string | null;
  created_at?: string;
  updated_at?: string;
};
